### ISSUE TITLE
[Feature Request] Related Content

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#50] opened 2018-11-23 10:29 UTC
Hello!

Listing related posts as "Related" or "See also" at the end of the post, increases user traction. May be we should have [Related Content](https://gohugo.io/content-management/related/) in Story?  

I am thinking more like [BeautifulHugo](https://themes.gohugo.io//theme/beautifulhugo/post/2017-03-20-photoswipe-gallery-sample/) or [min_night](https://themes.gohugo.io//theme/min_night/2014/04/02/getting-started-with-hugo/)  

Thanks!

**Comment by xaprb** [comment] 2018-11-29 14:38
Thanks for the idea! Duplicate of #17. Want to continue the conversation there?

**Closed by xaprb** 2018-11-29 14:38 UTC
